const navigationMenu = {
  id: 'dGVybToyNA==',
  name: 'Sports Helsinki Header FI',
  locations: ['PRIMARY'],
  menuItems: {
    nodes: [
      {
        id: 'cG9zdDoxNjI=',
        parentId: null,
        order: 1,
        path: '/haku',
        target: null,
        title: null,
        url: '/haku',
        label: 'Haku',
      },
      {
        id: 'cG9zdDoyOTc=',
        parentId: null,
        order: 2,
        path: '/pages/kohderyhmat',
        target: null,
        title: null,
        url: '/pages/kohderyhmat',
        label: 'Kohderyhmät',
      },
      {
        id: 'cG9zdDo5NTI1',
        parentId: 'cG9zdDoyOTc=',
        order: 3,
        path: '/fi/pages/kohderyhmat/lapset-ja-perheet/',
        target: null,
        title: null,
        url: 'https://liikunta.app-staging.hkih.hion.dev/fi/pages/kohderyhmat/lapset-ja-perheet/',
        label: 'Lapset ja perheet',
      },
      {
        id: 'cG9zdDo5NTIy',
        parentId: 'cG9zdDoyOTc=',
        order: 4,
        path: '/fi/pages/kohderyhmat/aikuiset/',
        target: null,
        title: null,
        url: 'https://liikunta.app-staging.hkih.hion.dev/fi/pages/kohderyhmat/aikuiset/',
        label: 'Aikuiset',
      },
      {
        id: 'cG9zdDozNDA=',
        parentId: null,
        order: 5,
        path: '/pages/liikuntapalvelut',
        target: null,
        title: null,
        url: '/pages/liikuntapalvelut',
        label: 'Tukea liikuntaan',
      },
      {
        id: 'cG9zdDo5NDUy',
        parentId: null,
        order: 6,
        path: '/fi/pages/kohderyhmat/kumppanit/tilojen-varaaminen/',
        target: null,
        title: null,
        url: 'https://liikunta.app-staging.hkih.hion.dev/fi/pages/kohderyhmat/kumppanit/tilojen-varaaminen/',
        label: 'Liikuntatilojen varaaminen',
      },
      {
        id: 'cG9zdDo5NjMw',
        parentId: 'cG9zdDo5NDUy',
        order: 7,
        path: '/fi/pages/liikuntapalvelut/maksut-ja-hinnasto/',
        target: null,
        title: null,
        url: 'https://liikunta.app-staging.hkih.hion.dev/fi/pages/liikuntapalvelut/maksut-ja-hinnasto/',
        label: 'Maksut ja hinnasto',
      },
      {
        id: 'cG9zdDo5NjMx',
        parentId: 'cG9zdDo5NDUy',
        order: 8,
        path: '/fi/pages/kohderyhmat/kumppanit/tilojen-varaaminen/ohjeet-vuorojen-hakemiseen/',
        target: null,
        title: null,
        url: 'https://liikunta.app-staging.hkih.hion.dev/fi/pages/kohderyhmat/kumppanit/tilojen-varaaminen/ohjeet-vuorojen-hakemiseen/',
        label: 'Ohjeet vuorojen hakemiseen',
      },
      {
        id: 'cG9zdDo5NjMy',
        parentId: 'cG9zdDo5NDUy',
        order: 9,
        path: '/fi/pages/kohderyhmat/kumppanit/tilojen-varaaminen/ohjeet-vuorojen-hakemiseen/%ef%bf%bc/',
        target: null,
        title: null,
        url: 'https://liikunta.app-staging.hkih.hion.dev/fi/pages/kohderyhmat/kumppanit/tilojen-varaaminen/ohjeet-vuorojen-hakemiseen/%ef%bf%bc/',
        label: 'Ohjeet vaalitilaisuuden tilavaraukseen',
      },
      {
        id: 'cG9zdDo5NjMz',
        parentId: 'cG9zdDo5NDUy',
        order: 10,
        path: '/fi/pages/kohderyhmat/kumppanit/tilojen-varaaminen/vuorojenjakokriteerit/',
        target: null,
        title: null,
        url: 'https://liikunta.app-staging.hkih.hion.dev/fi/pages/kohderyhmat/kumppanit/tilojen-varaaminen/vuorojenjakokriteerit/',
        label: 'Vuorojenjakokriteerit',
      },
      {
        id: 'cG9zdDo5NjM1',
        parentId: 'cG9zdDo5NDUy',
        order: 11,
        path: '/fi/pages/kohderyhmat/kumppanit/tilojen-varaaminen/liikuntapalvelun-hallinnoimat-koulutilat/',
        target: null,
        title: null,
        url: 'https://liikunta.app-staging.hkih.hion.dev/fi/pages/kohderyhmat/kumppanit/tilojen-varaaminen/liikuntapalvelun-hallinnoimat-koulutilat/',
        label: 'Liikuntapalvelun hallinnoimat koulutilat',
      },
      {
        id: 'cG9zdDo5NjM2',
        parentId: 'cG9zdDo5NjM1',
        order: 12,
        path: '/fi/pages/kohderyhmat/kumppanit/tilojen-varaaminen/liikuntapalvelun-hallinnoimat-koulutilat/helsingin-kaupungin-koulujen-liikuntasalien-vapaa-ajan-kaytto/',
        target: null,
        title: null,
        url: 'https://liikunta.app-staging.hkih.hion.dev/fi/pages/kohderyhmat/kumppanit/tilojen-varaaminen/liikuntapalvelun-hallinnoimat-koulutilat/helsingin-kaupungin-koulujen-liikuntasalien-vapaa-ajan-kaytto/',
        label: 'Helsingin kaupungin koulujen liikuntasalien vapaa-ajan käyttö',
      },
      {
        id: 'cG9zdDo5NjM3',
        parentId: 'cG9zdDo5NjM1',
        order: 13,
        path: '/fi/pages/kohderyhmat/kumppanit/tilojen-varaaminen/liikuntapalvelun-hallinnoimat-koulutilat/koulujen-liikuntasalien-itsenainen-kaytto/',
        target: null,
        title: null,
        url: 'https://liikunta.app-staging.hkih.hion.dev/fi/pages/kohderyhmat/kumppanit/tilojen-varaaminen/liikuntapalvelun-hallinnoimat-koulutilat/koulujen-liikuntasalien-itsenainen-kaytto/',
        label: 'Koulujen liikuntasalien itsenäinen käyttö',
      },
    ],
  },
};

export default navigationMenu;
