services:
  app:
    container_name: react-helsinki-headless-cms
    build:
      context: .
      target: ${DOCKER_TARGET:-development}
    ports:
      - '3000:3000'
      - '6006:6006' # Storybook
    volumes:
      - .:/app/
      - /app/node_modules # Exclude node_modules
