# Base SonarQube configuration for City of Helsinki Frontend projects
sonar.projectKey = city-of-helsinki_react-helsinki-headless-cms
sonar.organization=city-of-helsinki
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.sourceEncoding=UTF-8

# react-helsinki-headless-cms specific
sonar.projectName=react-helsinki-headless-cms

sonar.sources=src
sonar.exclusions= \
  **/__mocks__/**/*, \
  **/__snapshots__/*, \
  **/*.d.ts

sonar.test.inclusions= \
  **/__tests__/**/*,  \
  **/*.test.js, \
  **/*.test.ts, \
  **/*.test.jsx, \
  **/*.test.tsx

sonar.coverage.exclusions= \
  **/*.stories.tsx, \
  **/index.tsx, \
  **/index.ts, \
  **/index.js, \
  **/index.jsx

# Ignore "Refactor this code to not nest functions more than 4 levels deep." in test files,
# because it's mostly raised when describe-functions are used.
#
# Rule: typescript:S2004
# Name: "Refactor this code to not nest functions more than 4 levels deep."
# URL: https://rules.sonarsource.com/typescript/RSPEC-2004/
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S2004
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.test.tsx

# Ignore "Using pseudorandom number generators (PRNGs) is security-sensitive" in stoyry book files.
# because it is safe in a non-security related Storybook demo file.
#
# Rule: typescript:S2245
# Name: "Using pseudorandom number generators (PRNGs) is security-sensitive"
# URL:
# - https://rules.sonarsource.com/typescript/RSPEC-2245/
# - https://sonarcloud.io/organizations/city-of-helsinki/rules?open=typescript%3AS2245&rule_key=typescript%3AS2245
sonar.issue.ignore.multicriteria.e2.ruleKey=typescript:S2245
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.stories.tsx
