import React from 'react';

import { render, screen, waitFor } from '../../../common/utils/testingLibrary';
import { server } from '../../../mocks/server';
import { CmsEndpoint } from '../../../storybook-common/constants';
import { getApolloConfig } from '../../../tests/apolloConfig';
import { Navigation } from '../Navigation';

// Establish API mocking before all tests.
beforeAll(() => {
  server.listen();
});

afterEach(() => {
  jest.resetAllMocks();
});

describe('apollo navigation component', () => {
  it('renders navigation with gql data', async () => {
    render(
      <Navigation
        onTitleClick={() => {}}
        menuName="Hobbies Helsinki Header FI"
        getPathnameForLanguage={() => '#'}
      />,
      undefined,
      {
        ...getApolloConfig(CmsEndpoint.hobbies),
      },
    );

    // wait data to load
    await waitFor(() => {
      expect(screen.queryByText('English')).toBeInTheDocument();
    });

    // there should be 3 language navigation items
    expect(screen.getByText('English')).toBeInTheDocument();
    expect(screen.getByText('Suomi')).toBeInTheDocument();
    expect(screen.getByText('Svenska')).toBeInTheDocument();

    // there should be 2 links Haku and Ajankohtaista generated by component
    expect(screen.getByRole('link', { name: 'Haku' })).toHaveAttribute(
      'href',
      '/haku',
    );
    expect(screen.getByRole('link', { name: 'Ajankohtaista' })).toHaveAttribute(
      'href',
      '/artikkelit',
    );
    expect(screen.getAllByRole('link').length).toBe(5);
  });
});
