name: publish canary

on:
  push:
    branches:
      - main

jobs:
  publish-npm-canary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: yarn test
      - run: yarn build
      - run: yarn publish-canary
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
